rules:
	class-name-format: 0
	force-attribute-nesting: 0
	force-element-nesting: 0
	force-pseudo-nesting: 0
	indentation:
		- 2
		-
			size: 'tab'
	nesting-depth: 0
	no-ids: 0
	no-important: 0
	no-qualifying-elements: 0
	no-vendor-prefixes: 0
	variable-name-format: 0
