import { defineConfig } from 'eslint/config'; // eslint-disable-line import/no-unresolved
import globals from 'globals';
import importPlugin from 'eslint-plugin-import';
import js from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';

export default defineConfig([
	{
		ignores: ['build/**/*', 'dist/**/*', 'public/assets/js/*.min.js', 'vendor/**/*'],
	},
	{
		files: ['cypress/**/*', '**/*.test.js'],
		languageOptions: {
			globals: {
				...globals.jest,
				before: 'readonly',
				context: 'readonly',
				cy: 'readonly',
				Cypress: 'readonly',
			},
		},
	},
	{
		files: ['**/*.js'],
		extends: [
			js.configs.recommended,
			importPlugin.flatConfigs.recommended,
		],
		languageOptions: {
			ecmaVersion: 'latest',
			globals: globals.browser,
		},
		plugins: {
			'@stylistic': stylistic,
		},
		rules: {
			...stylistic.configs.customize({
				indent: 'tab',
				semi: true,
			}).rules,
			'@stylistic/array-bracket-newline': ['error', 'consistent'],
			'@stylistic/arrow-parens': ['error', 'always'],
			'@stylistic/brace-style': ['error', '1tbs'],
			'@stylistic/comma-dangle': ['error', {
				arrays: 'always-multiline',
				objects: 'always-multiline',
				imports: 'always-multiline',
				exports: 'always-multiline',
				functions: 'never',
			}],
			'@stylistic/curly-newline': ['error', { minElements: 1 }],
			'@stylistic/function-call-argument-newline': ['error', 'consistent'],
			'@stylistic/function-call-spacing': ['error', 'never'],
			'@stylistic/function-paren-newline': ['error', 'consistent'],
			'@stylistic/jsx-newline': 0,
			'@stylistic/jsx-pascal-case': ['error'],
			'@stylistic/jsx-self-closing-comp': ['error'],
			'@stylistic/jsx-sort-props': ['error'],
			'@stylistic/linebreak-style': ['error', 'unix'],
			'@stylistic/max-len': ['error', 150],
			'@stylistic/multiline-ternary': 0,
			'@stylistic/newline-per-chained-call': 0, // TODO.
			'@stylistic/no-confusing-arrow': ['error'],
			'@stylistic/no-extra-semi': ['error'],
			'@stylistic/no-multi-spaces': ['error'],
			'@stylistic/object-curly-newline': [
				'error',
				{
					multiline: true,
					consistent: true,
				},
			],
			'@stylistic/one-var-declaration-per-line': ['error'],
			'@stylistic/padding-line-between-statements': ['error'],
			'@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
			'@stylistic/quote-props': ['error', 'as-needed'],
			'@stylistic/semi-style': ['error', 'last'],
			'@stylistic/switch-colon-spacing': ['error'],
			'array-callback-return': ['error'],
			'no-await-in-loop': ['error'],
			'no-constructor-return': ['error'],
			'no-duplicate-imports': ['error'],
			'no-inner-declarations': ['error'],
			'no-promise-executor-return': ['error'],
			'no-self-compare': ['error'],
			'no-template-curly-in-string': ['error'],
			'no-unassigned-vars': ['error'],
			'no-unmodified-loop-condition': ['error'],
			'no-unreachable-loop': ['error'],
			'no-useless-assignment': ['error'],
			'arrow-body-style': ['error'],
			'block-scoped-var': ['error'],
			camelcase: ['error', { properties: 'never' }],
			'capitalized-comments': ['error', 'always', { ignoreConsecutiveComments: true }],
			complexity: ['error'],
			'consistent-return': ['error'],
			'consistent-this': ['error'],
			curly: ['error'],
			'default-param-last': ['error'],
			'dot-notation': ['error'],
			eqeqeq: ['error'],
			'import/extensions': ['error', 'ignorePackages'],
			'import/first': 'error',
			'import/newline-after-import': 'error',
			'import/no-extraneous-dependencies': 'error',
			'import/no-absolute-path': 'error',
			'import/no-cycle': 'error',
			'import/no-self-import': 'error',
			'import/no-useless-path-segments': 'error',
			'import/no-deprecated': 'error',
			'max-classes-per-file': ['error'],
			'max-depth': ['warn'],
			'max-nested-callbacks': ['error'],
			'new-cap': ['error'],
			'no-alert': ['error'],
			'no-array-constructor': ['error'],
			'no-bitwise': ['error'],
			'no-console': ['error'],
			'no-else-return': ['error'],
			'no-eval': ['error'],
			'no-extend-native': ['error'],
			'no-implicit-coercion': ['error'],
			'no-implicit-globals': ['error'],
			'no-implied-eval': ['error'],
			'no-invalid-this': ['error'],
			'no-loop-func': ['error'],
			'no-multi-assign': ['error'],
			'no-negated-condition': ['error'],
			'no-nested-ternary': ['error'],
			'no-new-wrappers': ['error'],
			'no-new': ['error'],
			'no-object-constructor': ['error'],
			'no-plusplus': ['error'],
			'no-return-assign': ['error'],
			'no-script-url': ['error'],
			'no-sequences': ['error'],
			'no-shadow': ['error'],
			'no-throw-literal': ['error'],
			'no-unneeded-ternary': ['error'],
			'no-unused-expressions': ['error'],
			'no-useless-computed-key': ['error'],
			'no-useless-concat': ['error'],
			'no-useless-rename': ['error'],
			'no-useless-return': ['error'],
			'no-var': ['error'],
			'no-warning-comments': 0, // TODO.
			'object-shorthand': ['error'],
			'one-var': ['error', 'never'],
			'operator-assignment': ['error'],
			'prefer-arrow-callback': ['error'],
			'prefer-const': ['error'],
			'prefer-object-has-own': ['error'],
			'prefer-object-spread': ['error'],
			'prefer-promise-reject-errors': ['error'],
			'prefer-regex-literals': ['error'],
			'prefer-template': ['error'],
			'preserve-caught-error': ['error'],
			radix: ['error'],
			'require-await': ['error'],
			'sort-imports': ['error', { ignoreCase: true }],
			yoda: ['error'],
		},
	},
	{
		files: ['*.config.js'],
		languageOptions: {
			sourceType: 'module',
			globals: globals.node,
		},
	},
]);
