name: JS
on: [push]
jobs:
  ci:
    name: JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/checkout@v3
    - run: yarn install
    - run: yarn run lint
